source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
workspace 'Viewfinder.xcworkspace'
project 'Viewfinder.xcodeproj'

target 'Viewfinder' do
  # Pods for Viewfinder

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'#, :subspecs => [
  #'Core',
  #'RCTActionSheet',
  #'RCTGeolocation',
  #'RCTImage',
  #'RCTLinkingIOS',
  #'RCTNetwork',
  #'RCTSettings',
  #'RCTText',
  #'RCTVibration',
  #'RCTWebSocket'
  #]

  pod 'GoogleMaps', '~> 2.1.1' # <~~ remove this line if you do not want to support GoogleMaps on iOS
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info/'
  
  #pod 'Firebase/Core'
  pod 'HockeySDK', :subspecs => ['AllFeaturesLib']

end
