// src/actions/actionTypes.js

const ACTION_TYPES = {
  MARKER_CLICK: 'MARKER_CLICK',
  SWITCH_MENU_CONTENT_VIEW: 'SWITCH_MENU_CONTENT_VIEW',
  SWITCH_LANDING_PAGE_VIEW: 'SWITCH_LANDING_PAGE_VIEW',
  SELECT_MARKER: 'SELECT_MARKER',
  SELECT_GUIDE: 'SELECT_GUIDE',
  ADD_BOOKMARK: 'ADD_BOOKMARK',
  REMOVE_BOOKMARK: 'REMOVE_BOOKMARK',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
};

export default ACTION_TYPES;
